class Text:
    def backspace(self, cursor: Cursor): ...
    def delete(self, cursor: Cursor): ...
    def delete_selection(self, selection: Selection): ...
    def insert(self, cursor: Cursor, text: str): ...

class GUI:
    def backspace(self):
        self.text.backspace(self.cursor)

    def delete(self):
        self.text.delete(self.cursor)
