present:
  presenterm --publish-speaker-notes --theme tokyonight-night main.md
listen:
  presenterm --listen-speaker-notes --theme tokyonight-night main.md
clean:
  rm -rf demos/git
  mkdir -p demos/git
